prog3050/PROG3050_CVGSClub/Controllers/GameLibrariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PROG3050_CVGSClub.Models;

namespace PROG3050_CVGSClub.Controllers
{
    public class GameLibrariesController : Controller
    {
        private readonly CvgsClubContext _context;

        public GameLibrariesController(CvgsClubContext context)
        {
            _context = context;
        }

        // GET: GameLibraries
        [Authorize]
        public async Task<IActionResult> Index()
        {
            string memberId = HttpContext.Session.GetString("userId");
            string url = "/Identity/Account/Login";
            if (memberId == null)
            {
                return LocalRedirect(url);
            }
            else
            {
                var cvgsClubContext = _context.GamesLibrary.Include(g => g.Game).Include(g => g.Member).Where(g => g.MemberId == memberId);
                return View(await cvgsClubContext.ToListAsync());
            }
        }

        // GET: GameLibraries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gamesLibrary = await _context.GamesLibrary
                .Include(g => g.Game)
                .Include(g => g.Member)
                .FirstOrDefaultAsync(m => m.LibraryGameId == id);
            if (gamesLibrary == null)
            {
                return NotFound();
            }

            return View(gamesLibrary);
        }

        // GET: GameLibraries/Create
        public IActionResult Create()
        {
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "AvailablePlatforms");
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId");
            return View();
        }

        // POST: GameLibraries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LibraryGameId,MemberId,GameId")] GamesLibrary gamesLibrary)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gamesLibrary);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "AvailablePlatforms", gamesLibrary.GameId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", gamesLibrary.MemberId);
            return View(gamesLibrary);
        }

        // GET: GameLibraries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gamesLibrary = await _context.GamesLibrary.FindAsync(id);
            if (gamesLibrary == null)
            {
                return NotFound();
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "AvailablePlatforms", gamesLibrary.GameId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", gamesLibrary.MemberId);
            return View(gamesLibrary);
        }

        // POST: GameLibraries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LibraryGameId,MemberId,GameId")] GamesLibrary gamesLibrary)
        {
            if (id != gamesLibrary.LibraryGameId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gamesLibrary);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GamesLibraryExists(gamesLibrary.LibraryGameId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "AvailablePlatforms", gamesLibrary.GameId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", gamesLibrary.MemberId);
            return View(gamesLibrary);
        }

        // GET: GameLibraries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gamesLibrary = await _context.GamesLibrary
                .Include(g => g.Game)
                .Include(g => g.Member)
                .FirstOrDefaultAsync(m => m.LibraryGameId == id);
            if (gamesLibrary == null)
            {
                return NotFound();
            }

            return View(gamesLibrary);
        }

        // POST: GameLibraries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gamesLibrary = await _context.GamesLibrary.FindAsync(id);
            _context.GamesLibrary.Remove(gamesLibrary);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        // Check if Item exists
        private bool GamesLibraryExists(int id)
        {
            return _context.GamesLibrary.Any(e => e.LibraryGameId == id);
        }
    }
}

prog3050/PROG3050_CVGSClub/Controllers/GameReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PROG3050_CVGSClub.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace PROG3050_CVGSClub.Controllers
{
    public class GameReviewsController : Controller
    {
        private readonly CvgsClubContext _context;

        public GameReviewsController(CvgsClubContext context)
        {
            _context = context;
        }

        // GET: GameReviews
        [Authorize]
        public async Task<IActionResult> Index()
        {
            string memberId = HttpContext.Session.GetString("userId");
            string url = "/Identity/Account/Login";
            if (memberId == null)
            {
                return LocalRedirect(url);
            }
            else
            {
                var cvgsClubContext = _context.GameReviews.Include(g => g.Game).Include(g => g.Member).Where(m => m.MemberId == memberId);
                return View(await cvgsClubContext.ToListAsync());
            }  
        }

        // GET: GameReviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gameReviews = await _context.GameReviews
                .Include(g => g.Game)
                .Include(g => g.Member)
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (gameReviews == null)
            {
                return NotFound();
            }

            return View(gameReviews);
        }

        // GET: GameReviews/Create
        public IActionResult Create()
        {
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "GameName");
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId");
            ViewBag.GameId = ViewData["GameId"];

            return View();
        }

        // POST: GameReviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReviewId,MemberId,GameId,GameReview")] GameReviews gameReviews)
        {
            if (ModelState.IsValid)
            {
                if(gameReviews.GameReview == null)
				{
                    return View();
				}
                else
				{
                    gameReviews.MemberId = HttpContext.Session.GetString("userId");
                    _context.Add(gameReviews);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "GameName", gameReviews.GameId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", gameReviews.MemberId);

            return View(gameReviews);
        }

        // GET: GameReviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gameReviews = await _context.GameReviews.FindAsync(id);
            if (gameReviews == null)
            {
                return NotFound();
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "GameName", gameReviews.GameId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", gameReviews.MemberId);
            return View(gameReviews);
        }

        // POST: GameReviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewId,MemberId,GameId,GameReview")] GameReviews gameReviews)
        {
            if (id != gameReviews.ReviewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    gameReviews.MemberId = HttpContext.Session.GetString("userId");
                    _context.Update(gameReviews);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameReviewsExists(gameReviews.ReviewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "GameName", gameReviews.GameId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", gameReviews.MemberId);
            return View(gameReviews);
        }

        // GET: GameReviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gameReviews = await _context.GameReviews
                .Include(g => g.Game)
                .Include(g => g.Member)
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (gameReviews == null)
            {
                return NotFound();
            }

            return View(gameReviews);
        }

        // POST: GameReviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gameReviews = await _context.GameReviews.FindAsync(id);
            _context.GameReviews.Remove(gameReviews);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // Check if Item exists
        private bool GameReviewsExists(int id)
        {
            return _context.GameReviews.Any(e => e.ReviewId == id);
        }
    }
}

prog3050/PROG3050_CVGSClub/Views/GameLibraries/Create.cshtml
@model PROG3050_CVGSClub.Models.GamesLibrary

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>GamesLibrary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MemberId" class="control-label"></label>
                <select asp-for="MemberId" class ="form-control" asp-items="ViewBag.MemberId"></select>
            </div>
            <div class="form-group">
                <label asp-for="GameId" class="control-label"></label>
                <select asp-for="GameId" class ="form-control" asp-items="ViewBag.GameId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

prog3050/PROG3050_CVGSClub/Views/GameLibraries/Delete.cshtml
@model PROG3050_CVGSClub.Models.GamesLibrary

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GamesLibrary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Game)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Game.AvailablePlatforms)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Member.MemberId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LibraryGameId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

prog3050/PROG3050_CVGSClub/Views/GameLibraries/Details.cshtml
@model PROG3050_CVGSClub.Models.GamesLibrary

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>GamesLibrary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Game)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Game.AvailablePlatforms)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Member.MemberId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.LibraryGameId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

prog3050/PROG3050_CVGSClub/Views/GameLibraries/Edit.cshtml
@model PROG3050_CVGSClub.Models.GamesLibrary

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>GamesLibrary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LibraryGameId" />
            <div class="form-group">
                <label asp-for="MemberId" class="control-label"></label>
                <select asp-for="MemberId" class="form-control" asp-items="ViewBag.MemberId"></select>
                <span asp-validation-for="MemberId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GameId" class="control-label"></label>
                <select asp-for="GameId" class="form-control" asp-items="ViewBag.GameId"></select>
                <span asp-validation-for="GameId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

prog3050/PROG3050_CVGSClub/Views/GameLibraries/Index.cshtml
@model IEnumerable<PROG3050_CVGSClub.Models.GamesLibrary>

@{
    ViewData["Title"] = "Index";
}

<h2 style="text-align:center">Games Library</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Game)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Game.GameName)
                </td>
                <td>
                    <a asp-controller="GameReviews" asp-action="Create" asp-route-id="@item.GameId">Review</a>
                </td>
            </tr>
        }
    </tbody>
</table>