prog3050/PROG3050_CVGSClub/Models/Events.cs
using System;
using System.Collections.Generic;

namespace PROG3050_CVGSClub.Models
{
    public partial class Events
    {
        public Events()
        {
            MemberEvents = new HashSet<MemberEvents>();
        }

        public int EventId { get; set; }
        public string EventName { get; set; }
        public DateTime EventDate { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
        public int Capacity { get; set; }

        public ICollection<MemberEvents> MemberEvents { get; set; }
    }
}

prog3050/PROG3050_CVGSClub/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PROG3050_CVGSClub.Interfaces;
using PROG3050_CVGSClub.Models;

namespace PROG3050_CVGSClub.Controllers
{
    public class EventsController : Controller
    {
        private readonly CvgsClubContext _context;
        IEventService _eventService;

        public EventsController(CvgsClubContext context, IEventService eventService)
        {
            _context = context;
            _eventService = eventService;
        }

        // GET: Events
        [Authorize]
        public async Task<IActionResult> Index()
        {
            string memberId = HttpContext.Session.GetString("userId");
            string url = "/Identity/Account/Login";
            if (memberId == null)
            {
                return LocalRedirect(url);
            }
            else
            {
                return View(await _context.Events.ToListAsync());
            }
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var events = await _context.Events
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (events == null)
            {
                return NotFound();
            }

            return View(events);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventId,EventName,EventDate,StartTime,EndTime,Capacity")] Events events)
        {
            if (ModelState.IsValid)
            {
                _context.Add(events);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(events);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var events = await _context.Events.FindAsync(id);
            if (events == null)
            {
                return NotFound();
            }
            return View(events);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,EventName,EventDate,StartTime,EndTime,Capacity")] Events events)
        {
            if (id != events.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(events);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventsExists(events.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(events);
        }

        // POST Events/Subscribe
        // Takes in the Event ID and creates a MemberEvent object using the Event ID and Member ID
        public async Task<IActionResult> Subscribe(int id)
        {
            var events = await _context.Events.FindAsync(id);
            if (events == null)
            {
                return NotFound();
            }

			// Retrive the ID of the user currently signed in from the session object "userId"
			string memberId = HttpContext.Session.GetString("userId");

			// Will call upon the Create method of the MemberEventsController and supply the method with the newMemberEvent object
			// created in the interface file
			var memberEvent = new MemberEventsController(_context);
            await memberEvent.Create(_eventService.Subscribe(id, memberId));

            return View(events);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var events = await _context.Events
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (events == null)
            {
                return NotFound();
            }

            return View(events);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var events = await _context.Events.FindAsync(id);
            _context.Events.Remove(events);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // Check if event exists
        private bool EventsExists(int id)
        {
            return _context.Events.Any(e => e.EventId == id);
        }
    }
}

prog3050/PROG3050_CVGSClub/Controllers/MemberEventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PROG3050_CVGSClub.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace PROG3050_CVGSClub.Controllers
{
    public class MemberEventsController : Controller
    {
        private readonly CvgsClubContext _context;

        public MemberEventsController(CvgsClubContext context)
        {
            _context = context;
        }

        // GET: MemberEvents
        [Authorize]
        public async Task<IActionResult> Index()
        {
            string memberId = HttpContext.Session.GetString("userId");
            var cvgsClubContext = _context.MemberEvents.Include(m => m.Event).Include(m => m.Member).Where(m => m.MemberId == memberId);
            return View(await cvgsClubContext.ToListAsync());
        }

        // GET: MemberEvents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memberEvents = await _context.MemberEvents
                .Include(m => m.Event)
                .Include(m => m.Member)
                .FirstOrDefaultAsync(m => m.MemberEventsId == id);
            if (memberEvents == null)
            {
                return NotFound();
            }

            return View(memberEvents);
        }

        // GET: MemberEvents/Create
        public IActionResult Create()
        {
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventName");
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId");
            return View();
        }

        // POST: MemberEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemberEventsId,EventId,MemberId")] MemberEvents memberEvents)
        {
            if (ModelState.IsValid)
            {
                _context.Add(memberEvents);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventName", memberEvents.EventId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", memberEvents.MemberId);
            return View(memberEvents);
        }

        // GET: MemberEvents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memberEvents = await _context.MemberEvents.FindAsync(id);
            if (memberEvents == null)
            {
                return NotFound();
            }
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventName", memberEvents.EventId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", memberEvents.MemberId);
            return View(memberEvents);
        }

        // POST: MemberEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MemberEventsId,EventId,MemberId")] MemberEvents memberEvents)
        {
            if (id != memberEvents.MemberEventsId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(memberEvents);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberEventsExists(memberEvents.MemberEventsId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "EventName", memberEvents.EventId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", memberEvents.MemberId);
            return View(memberEvents);
        }

        // GET: MemberEvents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memberEvents = await _context.MemberEvents
                .Include(m => m.Event)
                .Include(m => m.Member)
                .FirstOrDefaultAsync(m => m.MemberEventsId == id);
            if (memberEvents == null)
            {
                return NotFound();
            }

            return View(memberEvents);
        }

        // POST: MemberEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var memberEvents = await _context.MemberEvents.FindAsync(id);
            _context.MemberEvents.Remove(memberEvents);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // Check if Item exists
        private bool MemberEventsExists(int id)
        {
            return _context.MemberEvents.Any(e => e.MemberEventsId == id);
        }
    }
}

prog3050/PROG3050_CVGSClub/Views/Events/Create.cshtml
@model PROG3050_CVGSClub.Models.Events

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Events</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDate" class="control-label"></label>
                <input asp-for="EventDate" class="form-control" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

prog3050/PROG3050_CVGSClub/Views/Events/Delete.cshtml
@model PROG3050_CVGSClub.Models.Events

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Events</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EventId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

prog3050/PROG3050_CVGSClub/Views/Events/Details.cshtml
@model PROG3050_CVGSClub.Models.Events

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Events</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>
    </dl>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

prog3050/PROG3050_CVGSClub/Views/Events/Edit.cshtml
@model PROG3050_CVGSClub.Models.Events

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Events</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EventId" />
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDate" class="control-label"></label>
                <input asp-for="EventDate" class="form-control" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

prog3050/PROG3050_CVGSClub/Views/Events/Index.cshtml
@model IEnumerable<PROG3050_CVGSClub.Models.Events>

@{
    ViewData["Title"] = "Index";
}

<h2 style="text-align:center">Events</h2>

<p>
	<a asp-area="" asp-controller="MemberEvents" asp-action="Index">View My Events</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Event Name
            </th>
            <th>
                Event Date
            </th>
            <th>
                Start Time
            </th>
            <th>
                End Time
            </th>
            <th>
                Capacity
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EventName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capacity)
            </td>
			<td>
				<a asp-action="Subscribe" asp-route-id="@item.EventId">Attend</a>
			</td>
        </tr>
}
    </tbody>
</table>

prog3050/PROG3050_CVGSClub/Views/Events/Subscribe.cshtml
@{
	ViewData["Title"] = "Subscribe";
}

<h2 style="text-align:center">Subscription Confirmation</h2>

<p>
	<a asp-area="" asp-controller="MemberEvents" asp-action="Index">View My Events</a>
</p>

<p>
	You have successfully subscribed to attend this event! If you wish to view all of your Events, please click above, otherwise please click <a asp-area="" asp-controller="Events" asp-action="Index">here</a>
</p>