prog3050/PROG3050_CVGSClub/Models/Games.cs
using System;
using System.Collections.Generic;

namespace PROG3050_CVGSClub.Models
{
    public partial class Games
    {
        public Games()
        {
            GameReviews = new HashSet<GameReviews>();
            GamesLibrary = new HashSet<GamesLibrary>();
            WishLists = new HashSet<WishLists>();
        }

        public int GameId { get; set; }
        public string GameName { get; set; }
        public decimal ListPrice { get; set; }
        public string ContentRating { get; set; }
        public string Genre { get; set; }
        public string AvailablePlatforms { get; set; }
        public string MaxPlayers { get; set; }

        public ICollection<GameReviews> GameReviews { get; set; }
        public ICollection<GamesLibrary> GamesLibrary { get; set; }
        public ICollection<WishLists> WishLists { get; set; }
    }
}

prog3050/PROG3050_CVGSClub/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using PROG3050_CVGSClub.Models;
using PROG3050_CVGSClub.Interfaces;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using PROG3050_CVGSClub.Helpers;

namespace PROG3050_CVGSClub.Controllers
{
    public class CartController : Controller
    {
        private readonly CvgsClubContext _context;
        private readonly CartDependency _cartDependency = new CartDependency();

        public CartController(CvgsClubContext context)
        {
            _context = context;
        }

        // GET: Cart
        [Authorize]
        public IActionResult Index()
        {
            string memberId = HttpContext.Session.GetString("userId");
            string url = "/Identity/Account/Login";
            if (memberId == null)
            {
                return LocalRedirect(url);
            }
            else
            {
                var cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                if (cart != null)
                {
                    ViewBag.cart = cart;
                    ViewBag.total = _cartDependency.TotalSum(cart);
                    ViewBag.tax = _cartDependency.TaxAmount(ViewBag.total);
                    ViewBag.final = _cartDependency.FinalCost(ViewBag.total, ViewBag.tax);
                }

                return View();
            }
        }
        
        // Checkout/buy items in cart 
        public IActionResult Buy(int id)
        {
            var games = _context.Games.FirstOrDefault(m => m.GameId == id);
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");

            if (cart == null)
            {
                cart = _cartDependency.AddToCart(games, null);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                cart = _cartDependency.BuyGame(id, cart, games);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }

            return RedirectToAction("Index");
        }

        //Remove game from cart
        public IActionResult Remove(int id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            cart = _cartDependency.RemoveGame(id, cart);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }


        //Checkout method that adds all items in the cart to the GameLibrary Table
        public async Task<IActionResult> CheckOut()
        {
            var memberId = HttpContext.Session.GetString("userId");
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");

            if (cart != null)
            {
                ViewBag.cart = cart;
                ViewBag.total = _cartDependency.TotalSum(cart);
                ViewBag.tax = _cartDependency.TaxAmount(ViewBag.total);
                ViewBag.final = _cartDependency.FinalCost(ViewBag.total, ViewBag.tax);

                // Do we really need to count the cart? There should only be one right?
                for (int i = 0; i < cart.Count; i++)
                {
                    GameLibrariesController gamesLibraryController = new GameLibrariesController(_context);
                    await gamesLibraryController.Create(_cartDependency.GameLibrary(cart, memberId, i));
                }
            }

            return View();
        }
    }
}

prog3050/PROG3050_CVGSClub/Controllers/GameLibrariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PROG3050_CVGSClub.Models;

namespace PROG3050_CVGSClub.Controllers
{
    public class GameLibrariesController : Controller
    {
        private readonly CvgsClubContext _context;

        public GameLibrariesController(CvgsClubContext context)
        {
            _context = context;
        }

        // GET: GameLibraries
        [Authorize]
        public async Task<IActionResult> Index()
        {
            string memberId = HttpContext.Session.GetString("userId");
            string url = "/Identity/Account/Login";
            if (memberId == null)
            {
                return LocalRedirect(url);
            }
            else
            {
                var cvgsClubContext = _context.GamesLibrary.Include(g => g.Game).Include(g => g.Member).Where(g => g.MemberId == memberId);
                return View(await cvgsClubContext.ToListAsync());
            }
        }

        // GET: GameLibraries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gamesLibrary = await _context.GamesLibrary
                .Include(g => g.Game)
                .Include(g => g.Member)
                .FirstOrDefaultAsync(m => m.LibraryGameId == id);
            if (gamesLibrary == null)
            {
                return NotFound();
            }

            return View(gamesLibrary);
        }

        // GET: GameLibraries/Create
        public IActionResult Create()
        {
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "AvailablePlatforms");
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId");
            return View();
        }

        // POST: GameLibraries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LibraryGameId,MemberId,GameId")] GamesLibrary gamesLibrary)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gamesLibrary);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "AvailablePlatforms", gamesLibrary.GameId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", gamesLibrary.MemberId);
            return View(gamesLibrary);
        }

        // GET: GameLibraries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gamesLibrary = await _context.GamesLibrary.FindAsync(id);
            if (gamesLibrary == null)
            {
                return NotFound();
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "AvailablePlatforms", gamesLibrary.GameId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", gamesLibrary.MemberId);
            return View(gamesLibrary);
        }

        // POST: GameLibraries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LibraryGameId,MemberId,GameId")] GamesLibrary gamesLibrary)
        {
            if (id != gamesLibrary.LibraryGameId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gamesLibrary);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GamesLibraryExists(gamesLibrary.LibraryGameId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "AvailablePlatforms", gamesLibrary.GameId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", gamesLibrary.MemberId);
            return View(gamesLibrary);
        }

        // GET: GameLibraries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gamesLibrary = await _context.GamesLibrary
                .Include(g => g.Game)
                .Include(g => g.Member)
                .FirstOrDefaultAsync(m => m.LibraryGameId == id);
            if (gamesLibrary == null)
            {
                return NotFound();
            }

            return View(gamesLibrary);
        }

        // POST: GameLibraries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gamesLibrary = await _context.GamesLibrary.FindAsync(id);
            _context.GamesLibrary.Remove(gamesLibrary);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        // Check if Item exists
        private bool GamesLibraryExists(int id)
        {
            return _context.GamesLibrary.Any(e => e.LibraryGameId == id);
        }
    }
}

prog3050/PROG3050_CVGSClub/Controllers/WishListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PROG3050_CVGSClub.Interfaces;
using PROG3050_CVGSClub.Models;

namespace PROG3050_CVGSClub.Controllers
{
    public class WishListsController : Controller
    {
        private readonly CvgsClubContext _context;
        private readonly WishListService _wishlistService = new WishListService();

        public WishListsController(CvgsClubContext context)
        {
            _context = context;
        }

        // GET: WishLists
        [Authorize]
        public async Task<IActionResult> Index()
        {
            string memberId = HttpContext.Session.GetString("userId");
            string url = "/Identity/Account/Login";
            if (memberId == null)
            {
                return LocalRedirect(url);
            }
            else
            {
                var cVGSClubContext = _context.WishLists.Include(w => w.Game).Include(w => w.Member).Where(w => w.MemberId == memberId);
                return View(await cVGSClubContext.ToListAsync());
            }
        }

        // GET: WishLists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wishLists = await _context.WishLists
                .Include(w => w.Game)
                .Include(w => w.Member)
                .FirstOrDefaultAsync(m => m.WishId == id);
            if (wishLists == null)
            {
                return NotFound();
            }

            return View(wishLists);
        }

        // GET: WishLists/Create
        public IActionResult Create()
        {
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "AvailablePlatforms");
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId");
            return View();
        }

        // POST: WishLists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WishId,MemberId,GameId")] WishLists wishLists)
        {
            if (ModelState.IsValid)
            {
                _context.Add(wishLists);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "AvailablePlatforms", wishLists.GameId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", wishLists.MemberId);
            return View(wishLists);
        }

        public async Task<IActionResult> AddWishlist(int id)
        {
            var game = await _context.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }

            string memberId = HttpContext.Session.GetString("userId");

            var wishLists = new WishListsController(_context);
            await wishLists.Create(_wishlistService.AddWishlist(id, memberId));

            return RedirectToAction("Index");
        }
        // GET: WishLists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wishLists = await _context.WishLists.FindAsync(id);
            if (wishLists == null)
            {
                return NotFound();
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "AvailablePlatforms", wishLists.GameId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", wishLists.MemberId);
            return View(wishLists);
        }

        // POST: WishLists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WishId,MemberId,GameId")] WishLists wishLists)
        {
            if (id != wishLists.WishId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(wishLists);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WishListsExists(wishLists.WishId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "GameId", "AvailablePlatforms", wishLists.GameId);
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", wishLists.MemberId);
            return View(wishLists);
        }

        // GET: WishLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wishLists = await _context.WishLists
                .Include(w => w.Game)
                .Include(w => w.Member)
                .FirstOrDefaultAsync(m => m.WishId == id);
            if (wishLists == null)
            {
                return NotFound();
            }

            return View(wishLists);
        }

        // POST: WishLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var wishLists = await _context.WishLists.FindAsync(id);
            _context.WishLists.Remove(wishLists);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // Check if Item exists
        private bool WishListsExists(int id)
        {
            return _context.WishLists.Any(e => e.WishId == id);
        }
    }
}

prog3050/PROG3050_CVGSClub/Views/Games/Create.cshtml
@model PROG3050_CVGSClub.Models.Games

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Games</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GameName" class="control-label"></label>
                <input asp-for="GameName" class="form-control" />
                <span asp-validation-for="GameName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ListPrice" class="control-label"></label>
                <input asp-for="ListPrice" class="form-control" />
                <span asp-validation-for="ListPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AvailablePlatforms" class="control-label"></label>
                <input asp-for="AvailablePlatforms" class="form-control" />
                <span asp-validation-for="AvailablePlatforms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxPlayers" class="control-label"></label>
                <input asp-for="MaxPlayers" class="form-control" />
                <span asp-validation-for="MaxPlayers" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

prog3050/PROG3050_CVGSClub/Views/Games/Delete.cshtml
@model PROG3050_CVGSClub.Models.Games

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Games</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GameName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GameName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ListPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ListPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContentRating)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContentRating)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AvailablePlatforms)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AvailablePlatforms)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaxPlayers)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaxPlayers)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GameId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

prog3050/PROG3050_CVGSClub/Views/Games/Details.cshtml
@model PROG3050_CVGSClub.Models.Games

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Games</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GameName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GameName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ListPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ListPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContentRating)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContentRating)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AvailablePlatforms)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AvailablePlatforms)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaxPlayers)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaxPlayers)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.GameId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

prog3050/PROG3050_CVGSClub/Views/Games/Edit.cshtml
@model PROG3050_CVGSClub.Models.Games

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Games</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GameId" />
            <div class="form-group">
                <label asp-for="GameName" class="control-label"></label>
                <input asp-for="GameName" class="form-control" />
                <span asp-validation-for="GameName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ListPrice" class="control-label"></label>
                <input asp-for="ListPrice" class="form-control" />
                <span asp-validation-for="ListPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContentRating" class="control-label"></label>
                <input asp-for="ContentRating" class="form-control" />
                <span asp-validation-for="ContentRating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AvailablePlatforms" class="control-label"></label>
                <input asp-for="AvailablePlatforms" class="form-control" />
                <span asp-validation-for="AvailablePlatforms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxPlayers" class="control-label"></label>
                <input asp-for="MaxPlayers" class="form-control" />
                <span asp-validation-for="MaxPlayers" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

prog3050/PROG3050_CVGSClub/Views/Games/Index.cshtml
@model IEnumerable<PROG3050_CVGSClub.Models.Games>

@{
    ViewData["Title"] = "Index";
}

<h2 style="text-align:center">Games</h2>

<span style="float:right;">
    <a asp-controller="GameLibraries" asp-action="Index">Game Library</a>
</span>


<table class="table">
    <thead>
        <tr>
            <th>
                Game Name
            </th>
            <th>
                List Price
            </th>
            <th>
                Content Rating
            </th>
            <th>
                Genre
            </th>
            <th>
                Available Platforms
            </th>
            <th>
                Max Players
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GameName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ListPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContentRating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AvailablePlatforms)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxPlayers)
                </td>
				<td>
					<a asp-controller="Cart" asp-action="Buy" asp-route-id="@item.GameId">Add to Cart</a> |
					<a asp-controller="WishLists" asp-action="AddWishlist" asp-route-id="@item.GameId">Add to Wishlist</a>
				</td>
            </tr>
        }
    </tbody>
</table>